add_newline = true
format = "$all"
right_format = "$time"
command_timeout = 2000

[nodejs]
symbol = "â¬¢ "
style = "bold green"

[docker_context]
symbol = "ğŸ³ "
style = "bold blue"

[golang]
symbol = "ğŸ¹ "
style = "bold cyan"

[kubernetes]
symbol = "ğŸ™"
style = "bold green"

[terraform]
symbol = "ğŸ— "
style = "bold blue"

[helm]
symbol = "â›µ "
style = "bold blue"

[aws]
symbol = "ğŸŒ "
style = "bold yellow"
format = "on [$symbol$profile]($style) "

[aws.region_aliases]
us-east-1 = "ğŸ‡ºğŸ‡¸ va"
us-east-2 = "ğŸ‡ºğŸ‡¸ oh"
us-west-1 = "ğŸ‡ºğŸ‡¸ ca"
us-west-2 = "ğŸ‡ºğŸ‡¸ or"
eu-central-1 = "ğŸ‡©ğŸ‡ª"
eu-west-1 = "ğŸ‡®ğŸ‡ª"
eu-west-2 = "ğŸ‡¬ğŸ‡§"
eu-west-3 = "ğŸ‡«ğŸ‡·"

[package]
symbol = "ğŸ“¦"
style = "bold yellow"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "ğŸŒ¿ "
style = "bold yellow"

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨Ã—$count "
behind = "ğŸ¢Ã—$count "
diverged = "ğŸ”± ğŸï¸ ğŸ’¨Ã—$ahead_count ğŸ¢ Ã—$behind_count"
untracked = "ğŸ›¤ï¸ Ã—$count "
stashed = "ğŸ“¦ "
modified = "ğŸ“Ã—$count "
staged = "ğŸ—ƒï¸ Ã—$count "
renamed = "ğŸ“›Ã—$count "
deleted = "ğŸ—‘ï¸ Ã—$count "
style = "bright-white"
format = "$all_status$ahead_behind "

[git_commit]
commit_hash_length = 8
style = "bold white"

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[username]
show_always = true
format = "[$user]($style)@"
style_root = "bold #FB94FF"
style_user = "bold #FF9D00"

[directory]
truncation_length = 8
truncate_to_repo = true
read_only = " ğŸ”’"
style = "bold #61AFEF"

[character]
error_symbol = "[âœ—](bold red) "

[cmd_duration]
min_time = 10000
format = " took [$duration]($style)"

[time]
disabled = false
style = "bold dimmed white"
format = "[$time]($style)"
